### PR TITLE
api: add 'file_id' into 'dumps()' method

### LINKED ISSUE #68: api: add ``file_id`` into jsonschema
We should add the ``file_id`` (i.e. FileInstance UUID) into the serialized record. This requires changing JSONSchema/Mapping/Marshmallow? Understand impact on existing services like CDS Videos and Zenodo of this change.

### PR DESCRIPTION
**Pull request by okraskaj**
* Closes #68

Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

### CODE REVIEW

**Comment by egabancho** [comment]
Do you think we should add a link to the file itself by default too? 
I always find myself either building the link on the interface or extending the `dumps`.

Don't have a string opinion about it though.

**Comment by Glignos** [comment]
In Zenodo it doesn't seem like it's affecting us since we are using:
https://github.com/zenodo/zenodo/blob/c50af9c590135a14e6359630d42c37a507f970d6/zenodo/modules/deposit/api.py#L79
https://github.com/zenodo/zenodo/blob/c50af9c590135a14e6359630d42c37a507f970d6/zenodo/modules/records/api.py#L134
In which we are replacing the added key: 
https://github.com/zenodo/zenodo/blob/c50af9c590135a14e6359630d42c37a507f970d6/zenodo/modules/records/api.py#L43
So when dumping a record or deposit the value should remain the same.

**Comment by ntarocco** [comment]
> Do you think we should add a link to the file itself by default too?
> I always find myself either building the link on the interface or extending the `dumps`.
> 
> Don't have a string opinion about it though.

I think it is a good idea, but I guess it should be added by the REST layer, not the api, no?

**Comment by ntarocco** [comment]
@Glignos @okraskaj 
The issue is that it is also affecting Invenio-Deposit, it is a dependency of it.
https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L280

In both Zenodo and CDS Videos we call `super`, so internally we need to ensure that nothing breaks in deposit.
* https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/api.py#L48
* https://github.com/CERNDocumentServer/cds-videos/blob/cdslabs/cds/modules/deposit/api.py#L262

In CDS Videos, we completely override everything:
https://github.com/CERNDocumentServer/cds-videos/blob/cdslabs/cds/modules/records/api.py#L122

I guess the safest thing is to test it on the instance, I will try to find some time tomorrow.

**Comment by ntarocco** [comment]
We have tested deposit/records-files in CDS Videos and everything works find.

**Pull request merged**
