### PR TITLE
api: files setter from dict

### LINKED ISSUE #21: api: improve API for bucket creation
**Problem:**
It is not intuitive that accessing `FilesMixin.files` will create a bucket if there is no bucket. A getter should not modify the database.

For B2Share deposits we want to create a bucket for every deposit. The bucket can later be deleted if the deposit is published without any file. The only way to do that with FilesMixin API is to call `deposit.files`. This looks more like a dead line of code than the creation of a bucket.

What's more, there is no way to know if a bucket exist with the API. One has to directly query the model. If, like I did, somebody tries to see if there are files in the serializer of invenio-records-rest, a bucket will be created automatically instead of saying that there are no files. This can create important bugs in case of rollback.

**Suggestion:**
- Add a method for creating the bucket. It could be a setter which takes a dict like this:

```
record.files = { 'hello.txt': BytesIO(b'Hello world!') }
```
- The `files` getter should not create a bucket if there is none. It can either return an iterator which ends immediately or return None. If an iterator is returned the bucket of the iterator should be `None`. That way it is explicit that there are no bucket.

### PR DESCRIPTION
**Pull request by jirikuncar**
- Adds method for creating files from a dict if any files have not been
  previously attached to the record.  (closes #21)

Signed-off-by: Jiri Kuncar jiri.kuncar@cern.ch

### CODE REVIEW

**Comment by nharraud** [comment]
What about using this setter as the default way to crete bucket instead of the `files` property? 

Something like that:
```python
    @files.setter
    def files(self, data):
         """Set files from data."""
         if self.model is None:
             raise MissingModelError()
 
         records_buckets = RecordsBuckets.query.filter_by(
             record_id=self.id).first()
 
         if not records_buckets:
             bucket = self._create_bucket()
             if not bucket:
                 raise RuntimeError('Cannot create bucket')
             RecordsBuckets.create(record=self.model, bucket=bucket)
         else:
             bucket = records_buckets.bucket
         current_files = self.files_iter_cls(self, bucket=bucket, file_cls=self.file_cls)
         if current_files:
             raise RuntimeError('Can not update existing files.')
         for key in data:
             current_files[key] = data[key]

         return current_files

    @property
    def files:
        """Get files iterator."""
         if self.model is None:
             raise MissingModelError()
 
         records_buckets = RecordsBuckets.query.filter_by(
             record_id=self.id).first()
 
         if not records_buckets:
             if not bucket:
                 return None
             RecordsBuckets.create(record=self.model, bucket=bucket)
         else:
             bucket = records_buckets.bucket

         return self.files_iter_cls(self, bucket=bucket, file_cls=self.file_cls)
```

Then the normal ways to initialize the bucket would be:
```python
if record.files is None:
  record.files = {}
# ...
record.files['world.txt'] = BytesIO(b'Hello world!')
```
Or
```python
files = record.files
if files is None:
  files = record.files = {}
files['world.txt'] = BytesIO(b'Hello world!')
```
Or the one in your test
```python
record.files = {'hello.txt': BytesIO(b'Hello world!')}
```

That way we avoid the lazy initialization and still have an easy bucket creation.

@jirikuncar @lnielsen WDYT?

**Comment by nharraud** [comment]
LGTM

**Comment by lnielsen** [comment]
LGTM

**Comment by lnielsen** [comment]
LGTM

**Pull request merged**
